/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControleRelatorio;
import Modelo.Cliente;
import Modelo.Funcionario;
import Modelo.Servico;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Negrão
 */
public class FrameRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameRelatorio2
     */
    public FrameRelatorio() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
        ArrayList<Cliente> arrayCli = new ArrayList<>();
        ArrayList<Funcionario> arrayFunc = new ArrayList<>();
        ArrayList<Servico> arrayServ = new ArrayList<>();
        ControleRelatorio cr1 = new ControleRelatorio();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        tfDia2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioCli = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jRadioFunc = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfMes1 = new javax.swing.JTextField();
        jRadioServ = new javax.swing.JRadioButton();
        btnGerar = new javax.swing.JButton();
        tfDia1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMes2 = new javax.swing.JTextField();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 5, true));

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("/");

        tfDia2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDia2.setPreferredSize(new java.awt.Dimension(40, 23));
        tfDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDia2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Filtrar atendimento por");

        buttonGroup1.add(jRadioCli);
        jRadioCli.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioCli.setText("Cliente");
        jRadioCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCliActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setPreferredSize(new java.awt.Dimension(300, 0));
        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("RELATÓRIOS");

        buttonGroup1.add(jRadioFunc);
        jRadioFunc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioFunc.setText("Funcionário");
        jRadioFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFuncActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("/");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("de");

        tfMes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfMes1.setPreferredSize(new java.awt.Dimension(40, 23));
        tfMes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMes1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioServ);
        jRadioServ.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioServ.setText("Serviço ");
        jRadioServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioServActionPerformed(evt);
            }
        });

        btnGerar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGerar.setText("GERAR");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        tfDia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDia1.setPreferredSize(new java.awt.Dimension(40, 23));
        tfDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDia1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("até");

        tfMes2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfMes2.setPreferredSize(new java.awt.Dimension(40, 23));
        tfMes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMes2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(btnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioCli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioFunc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioServ))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfDia2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfMes2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioCli)
                    .addComponent(jRadioFunc)
                    .addComponent(jRadioServ))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDia2ActionPerformed

    private void jRadioCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCliActionPerformed
        arrayCli=cr1.getControleCli();
        DefaultListModel dlm = new DefaultListModel();
        for(int i=0;i<arrayCli.size();i++){
            dlm.addElement(arrayCli.get(i).getNome_cli());
        }
        jList1.setModel(dlm);
        arrayCli.clear();
    }//GEN-LAST:event_jRadioCliActionPerformed

    private void jRadioFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFuncActionPerformed
        arrayFunc=cr1.getControleFunc();
        DefaultListModel dlm = new DefaultListModel();
        for(int i=0;i<arrayFunc.size();i++){
            dlm.addElement(arrayFunc.get(i).getNome_func());
        }
        jList1.setModel(dlm);
        arrayFunc.clear();
    }//GEN-LAST:event_jRadioFuncActionPerformed

    private void tfMes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMes1ActionPerformed

    private void jRadioServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioServActionPerformed
        arrayServ=cr1.getControleServ();
        DefaultListModel dlm = new DefaultListModel();
        for(int i=0;i<arrayServ.size();i++){
            dlm.addElement(arrayServ.get(i).getDescricao());
        }
        jList1.setModel(dlm);
        arrayServ.clear();
    }//GEN-LAST:event_jRadioServActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Fazer select com os dados");
    }//GEN-LAST:event_btnGerarActionPerformed

    private void tfDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDia1ActionPerformed

    private void tfMes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMes2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioCli;
    private javax.swing.JRadioButton jRadioFunc;
    private javax.swing.JRadioButton jRadioServ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfDia1;
    private javax.swing.JTextField tfDia2;
    private javax.swing.JTextField tfMes1;
    private javax.swing.JTextField tfMes2;
    // End of variables declaration//GEN-END:variables
}
