/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author leonardo corrá, giovani bertuzzo, gabriel negrão
 */
public class FramePrincipal extends javax.swing.JFrame {    
        
    /**
     * Creates new form NovoJFrame
     */
    public FramePrincipal() {
        initComponents();
        //this.jPanel2.setVisible(true);
        //c.repaint();
        //c.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCadCli = new javax.swing.JButton();
        btnCadFunc = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnAtendimento = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        jPanelPrinc = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadCli = new javax.swing.JMenuItem();
        jMenuCadFunc = new javax.swing.JMenuItem();
        jMenuCadServico = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuAgenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuCaixa = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuNovoAtend = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.white);

        btnCadCli.setText("cc");
        btnCadCli.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCliActionPerformed(evt);
            }
        });

        btnCadFunc.setText("cf");
        btnCadFunc.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncActionPerformed(evt);
            }
        });

        btnAgenda.setText("ag");
        btnAgenda.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        btnCaixa.setText("cx");
        btnCaixa.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });

        btnAtendimento.setText("fin at");
        btnAtendimento.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendimentoActionPerformed(evt);
            }
        });

        btnServicos.setText("ser");
        btnServicos.setPreferredSize(new java.awt.Dimension(50, 50));
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnServicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincLayout = new javax.swing.GroupLayout(jPanelPrinc);
        jPanelPrinc.setLayout(jPanelPrincLayout);
        jPanelPrincLayout.setHorizontalGroup(
            jPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanelPrincLayout.setVerticalGroup(
            jPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        jMenuCadCli.setText("Cliente");
        jMenuCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCliActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadCli);

        jMenuCadFunc.setText("Funcionário");
        jMenuCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadFuncActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadFunc);

        jMenuCadServico.setText("Serviço");
        jMenuCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadServicoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadServico);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Agenda");

        jMenuAgenda.setText("Consultar Agenda");
        jMenuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgendaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAgenda);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Caixa");

        jMenuCaixa.setText("Consultar Caixa");
        jMenuCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCaixaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCaixa);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Atendimento");

        jMenuNovoAtend.setText("Novo Atendimento");
        jMenuNovoAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoAtendActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuNovoAtend);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadFuncActionPerformed
       FrameCadFunc fcc1 = new FrameCadFunc();
       fcc1.setLocationRelativeTo(null);
       fcc1.setVisible(true);
    }//GEN-LAST:event_jMenuCadFuncActionPerformed

    private void jMenuCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCliActionPerformed
       FrameCadCli fcc1 = new FrameCadCli();
       fcc1.setLocationRelativeTo(null);
       fcc1.setVisible(true);
    }//GEN-LAST:event_jMenuCadCliActionPerformed

    private void jMenuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgendaActionPerformed
       FrameAgenda fa1 = new FrameAgenda();
       fa1.setLocationRelativeTo(null);
       fa1.setVisible(true);
    }//GEN-LAST:event_jMenuAgendaActionPerformed

    private void jMenuCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCaixaActionPerformed
       FrameCaixa fc1 = new FrameCaixa();
       fc1.setLocationRelativeTo(null);
       fc1.setVisible(true);
    }//GEN-LAST:event_jMenuCaixaActionPerformed

    private void btnCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCliActionPerformed
        FrameCadCli fcc1 = new FrameCadCli();
       fcc1.setLocationRelativeTo(null);
       fcc1.setVisible(true);
    }//GEN-LAST:event_btnCadCliActionPerformed

    private void btnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncActionPerformed
        FrameCadFunc fcc1 = new FrameCadFunc();
       fcc1.setLocationRelativeTo(null);
       fcc1.setVisible(true);
    }//GEN-LAST:event_btnCadFuncActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        FrameAgenda fa1 = new FrameAgenda();
       fa1.setLocationRelativeTo(null);
       fa1.setVisible(true);
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        FrameCaixa fc1 = new FrameCaixa();
       fc1.setLocationRelativeTo(null);
       fc1.setVisible(true);
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendimentoActionPerformed
       FrameAtendimento fa1 = new FrameAtendimento();
       fa1.setLocationRelativeTo(null); 
       fa1.setVisible(true);
    }//GEN-LAST:event_btnAtendimentoActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
       FrameServicos fa1 = new FrameServicos();
       fa1.setLocationRelativeTo(null); 
       fa1.setVisible(true);
    }//GEN-LAST:event_btnServicosActionPerformed

    private void jMenuNovoAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoAtendActionPerformed
        FrameAtendimento fa1 = new FrameAtendimento();
       fa1.setLocationRelativeTo(null); 
       fa1.setVisible(true);
    }//GEN-LAST:event_jMenuNovoAtendActionPerformed

    private void jMenuCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadServicoActionPerformed
       FrameServicos fa1 = new FrameServicos();
       fa1.setLocationRelativeTo(null); 
       fa1.setVisible(true);
    }//GEN-LAST:event_jMenuCadServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnAtendimento;
    private javax.swing.JButton btnCadCli;
    private javax.swing.JButton btnCadFunc;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnServicos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAgenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadCli;
    private javax.swing.JMenuItem jMenuCadFunc;
    private javax.swing.JMenuItem jMenuCadServico;
    private javax.swing.JMenuItem jMenuCaixa;
    private javax.swing.JMenuItem jMenuNovoAtend;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrinc;
    // End of variables declaration//GEN-END:variables
}
