/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author a1602020
 */
public class FrameAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form FrameAtendimento
     */
    public FrameAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdFunc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkBoxPintura = new javax.swing.JCheckBox();
        checkBoxChapinha = new javax.swing.JCheckBox();
        checkBoxSombrancelha = new javax.swing.JCheckBox();
        checkBoxMaquiagem = new javax.swing.JCheckBox();
        checkBoxEscova = new javax.swing.JCheckBox();
        checkBoxUnha = new javax.swing.JCheckBox();
        checkBoxMassagem = new javax.swing.JCheckBox();
        checkBoxCorte = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDataDia = new javax.swing.JTextField();
        txtDataMes = new javax.swing.JTextField();
        txtDataAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListAtendimentos = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblValorTotal1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblValorTotal2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("CONTROLE ATENDIMENTO");

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel3.setText("ID Cliente");

        txtIdCli.setEditable(false);
        txtIdCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdCliMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setText("ID Funcionário");

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel5.setText("Data");

        jLabel6.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel6.setText("Horário");

        txtIdFunc.setFont(new java.awt.Font("Droid Sans Fallback", 1, 18)); // NOI18N
        txtIdFunc.setForeground(new java.awt.Color(247, 89, 83));
        txtIdFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdFuncMouseClicked(evt);
            }
        });
        txtIdFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFuncActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("/");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("/");

        txtMin.setEditable(false);
        txtMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinMouseClicked(evt);
            }
        });
        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText(":");

        txtHora.setEditable(false);
        txtHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoraMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel9.setText("Selecione os serviços prestados:");

        checkBoxPintura.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxPintura.setText("Pintura");
        checkBoxPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPinturaActionPerformed(evt);
            }
        });

        checkBoxChapinha.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxChapinha.setText("Chapinha");
        checkBoxChapinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxChapinhaActionPerformed(evt);
            }
        });

        checkBoxSombrancelha.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxSombrancelha.setText("Sombrancelha");
        checkBoxSombrancelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSombrancelhaActionPerformed(evt);
            }
        });

        checkBoxMaquiagem.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxMaquiagem.setText("Maquiagem");
        checkBoxMaquiagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMaquiagemActionPerformed(evt);
            }
        });

        checkBoxEscova.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxEscova.setText("Escova");
        checkBoxEscova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEscovaActionPerformed(evt);
            }
        });

        checkBoxUnha.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxUnha.setText("Unha (Pé e mão)");
        checkBoxUnha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUnhaActionPerformed(evt);
            }
        });

        checkBoxMassagem.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxMassagem.setText("Massagem");
        checkBoxMassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMassagemActionPerformed(evt);
            }
        });

        checkBoxCorte.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        checkBoxCorte.setText("Corte");
        checkBoxCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCorteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setText("TOTAL:");

        lblValorTotal.setBackground(new java.awt.Color(92, 97, 108));
        lblValorTotal.setFont(new java.awt.Font("Droid Sans Fallback", 1, 18)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(228, 48, 46));
        lblValorTotal.setText("R$ 00,00");

        btnSalvar.setText("Finalizar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDataDia.setEditable(false);
        txtDataDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDataDiaMouseClicked(evt);
            }
        });

        txtDataMes.setEditable(false);
        txtDataMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDataMesMouseClicked(evt);
            }
        });

        txtDataAno.setEditable(false);
        txtDataAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDataAnoMouseClicked(evt);
            }
        });

        ListAtendimentos.setBackground(new java.awt.Color(197, 193, 193));
        ListAtendimentos.setForeground(new java.awt.Color(0, 0, 0));
        ListAtendimentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "0 - 08:00", "1 - 08:30", "2 - 09:00", "3 - 09:30" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListAtendimentos);

        jLabel11.setBackground(new java.awt.Color(92, 97, 108));
        jLabel11.setText("Atendimento - Hora:");

        jButton1.setText("Finalizar Pedido");

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel12.setText("TROCO");

        lblValorTotal1.setFont(new java.awt.Font("Droid Sans Fallback", 1, 18)); // NOI18N
        lblValorTotal1.setForeground(new java.awt.Color(78, 55, 246));
        lblValorTotal1.setText("R$ 00,00");

        jLabel14.setBackground(new java.awt.Color(92, 97, 108));
        jLabel14.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel14.setText("RECEBIDO");

        jTextField1.setFont(new java.awt.Font("Droid Sans Fallback", 1, 18)); // NOI18N

        lblValorTotal2.setBackground(new java.awt.Color(92, 97, 108));
        lblValorTotal2.setFont(new java.awt.Font("Droid Sans Fallback", 1, 18)); // NOI18N
        lblValorTotal2.setText("R$");

        jLabel2.setText("*campo necessário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addComponent(lblValorTotal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(checkBoxMaquiagem)
                                                    .addComponent(checkBoxEscova)
                                                    .addComponent(checkBoxUnha)
                                                    .addComponent(checkBoxMassagem)
                                                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(checkBoxCorte)
                                            .addComponent(checkBoxPintura)
                                            .addComponent(checkBoxChapinha)
                                            .addComponent(checkBoxSombrancelha))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblValorTotal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorTotal2)
                                        .addGap(0, 0, 0)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(txtDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxCorte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxPintura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxChapinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxSombrancelha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxMaquiagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxEscova)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxUnha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxMassagem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblValorTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorTotal2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblValorTotal1)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdCliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCliMouseClicked

    private void txtIdFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdFuncMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFuncMouseClicked

    private void txtMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinMouseClicked

    private void txtHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraMouseClicked

    private void checkBoxPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPinturaActionPerformed

    private void checkBoxChapinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxChapinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxChapinhaActionPerformed

    private void checkBoxSombrancelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSombrancelhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSombrancelhaActionPerformed

    private void checkBoxMaquiagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMaquiagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMaquiagemActionPerformed

    private void checkBoxEscovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxEscovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxEscovaActionPerformed

    private void checkBoxUnhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUnhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxUnhaActionPerformed

    private void checkBoxMassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMassagemActionPerformed

    private void checkBoxCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCorteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDataDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDataDiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDiaMouseClicked

    private void txtDataMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDataMesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataMesMouseClicked

    private void txtDataAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDataAnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAnoMouseClicked

    private void txtIdFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFuncActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListAtendimentos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkBoxChapinha;
    private javax.swing.JCheckBox checkBoxCorte;
    private javax.swing.JCheckBox checkBoxEscova;
    private javax.swing.JCheckBox checkBoxMaquiagem;
    private javax.swing.JCheckBox checkBoxMassagem;
    private javax.swing.JCheckBox checkBoxPintura;
    private javax.swing.JCheckBox checkBoxSombrancelha;
    private javax.swing.JCheckBox checkBoxUnha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotal1;
    private javax.swing.JLabel lblValorTotal2;
    private javax.swing.JTextField txtDataAno;
    private javax.swing.JTextField txtDataDia;
    private javax.swing.JTextField txtDataMes;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdCli;
    private javax.swing.JTextField txtIdFunc;
    private javax.swing.JTextField txtMin;
    // End of variables declaration//GEN-END:variables
}
