/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControleAlterInsert;
import Controle.ControleCadastroFunc;
import Controle.ControleCargo;
import Modelo.Cargo;
import Modelo.Cliente;
import Modelo.Funcionario;
import Modelo.Login;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class FrameCadFunc extends javax.swing.JInternalFrame {

    private Funcionario funcionario;
    private Login funcionario_login;
    private int objetoBuscado = 0;

    /**
     * Creates new form FrameCadFunc2
     */
    public FrameCadFunc() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        Xclose.setVisible(false);
        ControleCargo cc1 = new ControleCargo();
        ArrayList<Cargo> cargoList = cc1.getCargoList();
        for (int i = 0; i < cargoList.size(); i++) {
            boxCargo.addItem(cargoList.get(i).getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxCargo = new javax.swing.JComboBox<>();
        txtCpf2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCpf3 = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCpf4 = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtPis = new javax.swing.JTextField();
        txtCpf1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        Xclose = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 5, true));
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(647, 601));
        setPreferredSize(new java.awt.Dimension(647, 601));

        boxCargo.setEnabled(false);
        boxCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxCargoMouseClicked(evt);
            }
        });
        boxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCargoActionPerformed(evt);
            }
        });

        txtCpf2.setEnabled(false);
        txtCpf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpf2ActionPerformed(evt);
            }
        });
        txtCpf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpf2KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE FUNCIONÁRIOS");

        txtCpf3.setEnabled(false);
        txtCpf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpf3KeyPressed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Data Nasc");

        txtCpf4.setEnabled(false);
        txtCpf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpf4KeyPressed(evt);
            }
        });

        txtDia.setEnabled(false);
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaKeyPressed(evt);
            }
        });

        txtMes.setEnabled(false);
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMesKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Nome");
        jLabel8.setPreferredSize(new java.awt.Dimension(19, 22));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("CPF");

        txtAno.setEnabled(false);
        txtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnoKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Usuário");

        txtUser.setEnabled(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Senha");

        txtSenha.setEnabled(false);

        jButton3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cargo");

        txtPis.setEnabled(false);

        txtCpf1.setEnabled(false);
        txtCpf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpf1KeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("PIS");

        txtEstado.setText("Busque para editar.");

        Xclose.setForeground(new java.awt.Color(255, 0, 51));
        Xclose.setText("X");
        Xclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XcloseActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCpf4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPis)
                                        .addComponent(boxCargo, 0, 179, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Xclose)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(txtEstado))
                        .addContainerGap(87, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Xclose)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtPis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxCargoMouseClicked

    }//GEN-LAST:event_boxCargoMouseClicked

    private void boxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCargoActionPerformed
        boxCargo.getSelectedItem();
    }//GEN-LAST:event_boxCargoActionPerformed

    private void txtCpf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpf2ActionPerformed

    private void txtCpf2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpf2KeyPressed
        if (txtCpf2.getText().length() == 2) {
            txtCpf3.grabFocus();
        }
    }//GEN-LAST:event_txtCpf2KeyPressed

    private void txtCpf3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpf3KeyPressed
        if (txtCpf3.getText().length() == 2) {
            txtCpf4.grabFocus();
        }
    }//GEN-LAST:event_txtCpf3KeyPressed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtCpf4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpf4KeyPressed
        if (txtCpf4.getText().length() == 1) {
            boxCargo.grabFocus();
        }
    }//GEN-LAST:event_txtCpf4KeyPressed

    private void txtDiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyPressed
        if (txtDia.getText().length() == 1) {
            txtMes.grabFocus();
        }
    }//GEN-LAST:event_txtDiaKeyPressed

    private void txtMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyPressed
        if (txtMes.getText().length() == 1) {
            txtAno.grabFocus();
        }
    }//GEN-LAST:event_txtMesKeyPressed

    private void txtAnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoKeyPressed
        if (txtAno.getText().length() == 3) {
            txtSenha.grabFocus();
        }
    }//GEN-LAST:event_txtAnoKeyPressed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int retorno = -1;
        int soma = 0;
        if (objetoBuscado == 1 && verificaEdicao()) {
            retorno = JOptionPane.showConfirmDialog(null, "Deseja Editar o Funcionario já cadastrado?");
            if (retorno == 0) {
                try {
                    String stringFunc = "Update salaozao.funcionario SET";
                    if (!funcionario.getNome_func().equals(txtNome.getText())) {
                        stringFunc += " nome_func = '" + txtNome.getText() + "'";
                        soma++;
                    }
                    if (!funcionario.getPis_func().equals(txtPis.getText())) {
                        if (soma >= 1) {
                            stringFunc += ",";
                        }
                        stringFunc += " pis_func = '" + txtPis.getText() + "'";
                        soma++;
                    }
                    if (funcionario.getCargo_id() != boxCargo.getSelectedIndex()) {
                        if (soma >= 1) {
                            stringFunc += ",";
                        }
                        stringFunc += " cargo_id = " + boxCargo.getSelectedIndex();
                        soma++;
                    }
                    String cpf = txtCpf1.getText() + txtCpf2.getText() + txtCpf3.getText() + txtCpf4.getText();
                    if (!funcionario.getCpf_func().equals(cpf)) {
                        if (soma >= 1) {
                            stringFunc += ",";
                        }
                        soma++;
                        stringFunc += " cpf_func = '" + cpf + "'";
                    }
                    String data_nasc = txtAno.getText() + "-" + txtMes.getText() + "-" + txtDia.getText();
                    if (!String.valueOf(funcionario.getNasc()).equals(data_nasc)) {
                        if (soma >= 1) {
                            stringFunc += ",";
                        }
                        soma++;
                        stringFunc += " nasc = '" + data_nasc + "'";
                    }
                    stringFunc += " WHERE id_func = " + funcionario.getId_func();

                    soma = 0;
                    String stringLogin = "Update salaozao.login SET";
                    if (!funcionario_login.getUser().equals(txtUser.getText())) {
                        soma = 1;
                        stringLogin += " user = '" + txtUser.getText() + "'";
                    }
                    if (!funcionario_login.getSenha().equals(txtSenha.getText())) {
                        if (soma == 1) {
                            stringLogin += ", ";
                        }
                        stringLogin += " senha = '" + txtSenha.getText() + "'";
                    }
                    stringLogin += " WHERE id_login = " + funcionario.getLogin_id();

                    System.out.println(stringLogin);
                    ControleAlterInsert alter;
                    System.out.println(stringFunc);
                    if (!stringFunc.equals("Update salaozao.funcionario SET WHERE id_func = " + funcionario.getId_func())) {
                        alter = new ControleAlterInsert(stringFunc);
                    }
                    if (!stringLogin.equals("Update salaozao.login SET WHERE id_login = " + funcionario.getLogin_id())) {
                        alter = new ControleAlterInsert(stringLogin);
                    }
                    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(FrameCadCli.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (retorno == 1) {
                limpaRegistros();
                objetoBuscado = 0;
                Xclose.setVisible(false);
                jButton1.setVisible(true);

            }

        } else if (objetoBuscado == 1) {
            JOptionPane.showMessageDialog(null, "Usuario não Editado!");
        } else {
            String nome = txtNome.getText();
            String cpf = txtCpf1.getText() + txtCpf2.getText() + txtCpf3.getText() + txtCpf4.getText();
            String data = txtAno.getText() + "-" + txtMes.getText() + "-" + txtDia.getText();
            String pis = txtPis.getText();
            String user = txtUser.getText();
            String senha = txtSenha.getText();
            String cargo = String.valueOf(boxCargo.getSelectedIndex());

            Date date = new Date(System.currentTimeMillis());
            int atual = date.getYear() + 1900;
            atual -= Integer.parseInt(txtAno.getText());
            if (date.getMonth() + 1 < Integer.parseInt(txtMes.getText())) {
                atual -= 1;
            } else if (date.getMonth() + 1 == Integer.parseInt(txtMes.getText())) {
                if (date.getDate() > Integer.parseInt(txtDia.getText())) {
                    atual -= 1;
                }
            }
            String idade = String.valueOf(atual);
            try {
                ControleCadastroFunc novo_func = new ControleCadastroFunc(idade, nome, cpf, pis, cargo, user, senha, data);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(FrameCadFunc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCpf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpf1KeyPressed
        if (txtCpf1.getText().length() == 2) {
            txtCpf2.grabFocus();
        }
    }//GEN-LAST:event_txtCpf1KeyPressed

    private void XcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XcloseActionPerformed
        funcionario = null;
        limpaRegistros();
        objetoBuscado = 0;
        Xclose.setVisible(false);
        txtEstado.setText("Busque para editar.");
        jButton1.setVisible(true);
    }//GEN-LAST:event_XcloseActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE && txtBuscar.getText().length() == 1) {
            Xclose.doClick();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o Campo ID!");
        }
        ControleCadastroFunc func_busca = new ControleCadastroFunc(Integer.valueOf(txtBuscar.getText()));
        funcionario = func_busca.getFuncionario();
        funcionario_login = func_busca.getFuncionario_login();

        txtNome.setText(funcionario.getNome_func());
        txtPis.setText(funcionario.getPis_func());

        String cpf_func = funcionario.getCpf_func();
        txtCpf1.setText(cpf_func.substring(0, 3));
        txtCpf2.setText(cpf_func.substring(3, 6));
        txtCpf3.setText(cpf_func.substring(6, 9));
        txtCpf4.setText(cpf_func.substring(9, 11));

        boxCargo.setSelectedIndex(funcionario.getCargo_id());

        txtUser.setText(funcionario_login.getUser());
        txtSenha.setText(funcionario_login.getSenha());

        String nasc = String.valueOf(funcionario.getNasc());
        txtAno.setText(nasc.substring(0, 4));
        txtMes.setText(nasc.substring(5, 7));
        txtDia.setText(nasc.substring(8, 10));

        jButton1.setVisible(false);
        objetoBuscado = 1;
        txtEstado.setText("Clique no X para excluir busca e cadastrar novo");
        Xclose.setVisible(true);
        txtAno.enable(true);
        txtCpf1.enable(true);
        txtCpf2.enable(true);
        txtCpf3.enable(true);
        txtCpf4.enable(true);
        txtDia.enable(true);
        txtEstado.enable(true);
        txtMes.enable(true);
        txtNome.enable(true);
        txtSenha.enable(true);
        txtUser.enable(true);
        txtPis.enable(true);
        boxCargo.enable(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtBuscar.setText("");
        txtAno.setText("");
        txtMes.setText("");
        txtDia.setText("");
        txtCpf1.setText("");
        txtCpf2.setText("");
        txtCpf3.setText("");
        txtCpf4.setText("");
        txtNome.setText("");
        txtPis.setText("");
        txtSenha.setText("");
        txtUser.setText("");
        txtBuscar.enable(false);
        txtAno.enable(true);
        txtCpf1.enable(true);
        txtCpf2.enable(true);
        txtCpf3.enable(true);
        txtCpf4.enable(true);
        txtDia.enable(true);
        txtEstado.enable(true);
        txtMes.enable(true);
        txtNome.enable(true);
        txtSenha.enable(true);
        txtUser.enable(true);
        txtPis.enable(true);
        boxCargo.enable(true);
        txtNome.grabFocus();

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Xclose;
    private javax.swing.JComboBox<String> boxCargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCpf1;
    private javax.swing.JTextField txtCpf2;
    private javax.swing.JTextField txtCpf3;
    private javax.swing.JTextField txtCpf4;
    private javax.swing.JTextField txtDia;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPis;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void limpaRegistros() {
        txtBuscar.setText("");
        txtAno.setText("");
        txtMes.setText("");
        txtDia.setText("");
        txtCpf1.setText("");
        txtCpf2.setText("");
        txtCpf3.setText("");
        txtCpf4.setText("");
        txtNome.setText("");
        txtPis.setText("");
        txtSenha.setText("");
        txtUser.setText("");
        txtBuscar.enable(true);
        txtAno.enable(false);
        txtCpf1.enable(false);
        txtCpf2.enable(false);
        txtCpf3.enable(false);
        txtCpf4.enable(false);
        txtDia.enable(false);
        txtEstado.enable(false);
        txtMes.enable(false);
        txtNome.enable(false);
        txtSenha.enable(false);
        txtUser.enable(false);
        txtPis.enable(false);
        boxCargo.enable(false);
    }

    private boolean verificaEdicao() {
        int soma = 0;

        if (!funcionario.getNome_func().equals(txtNome.getText())) {
            soma++;
        }
        if (!funcionario.getPis_func().equals(txtPis.getText())) {
            soma++;
        }
        String cpf = txtCpf1.getText() + txtCpf2.getText() + txtCpf3.getText() + txtCpf4.getText();
        if (!funcionario.getCpf_func().equals(cpf)) {
            soma++;
        }
        if (funcionario.getCargo_id() != boxCargo.getSelectedIndex()) {
            soma++;
        }
        String data_nasc = txtDia.getText() + txtMes.getText() + txtAno.getText();
        if (!funcionario.getNasc().equals(data_nasc)) {
            soma++;
        }
        if (!funcionario_login.getUser().equals(txtUser.getText())) {
            soma++;
        }
        if (!funcionario_login.getSenha().equals(txtSenha.getText())) {
            soma++;
        }

        if (soma > 0) {
            return true;
        } else {
            return false;
        }
    }
}
